services:
  beszel-proxy:
    build: .
    network_mode: host
    environment:
      - BESZEL_HOST=localhost:8090
      - BESZEL_EMAIL=you@example.com
      - BESZEL_PASSWORD=yourpassword
      - LISTEN_PORT=6767
      - CORS_ORIGIN=*.prigoana.com
    restart: unless-stopped
